name: SkyUtilities
version: 0.3-SNAPSHOT
main: fr.skybuild.skyutilities.SkyUtilities
api-version: 1.20
softdepend: [TAB]

commands:
  maintenance:
    description: Active, désactive ou affiche le statut de la maintenance
    usage: /maintenance <on|off|status|reload> [durée]
    permission: maintenance.toggle

permissions:
  maintenance.toggle:
    description: Permet d’activer ou désactiver la maintenance
    default: false
  maintenance.whitelist:
    description: Permet de rester connecté pendant la maintenance
    default: false
  maintenance.status:
    description: Permet de voir le statut de la maintenance
    default: false
  maintenance.reload:
    description: Permet de recharger la configuration
    default: false
